name: Run rspec, rubocop

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: Run rspec
        run: bundle exec rspec
